export const metadata={title:'AuthiChain for Government — Federal Supply Chain Authentication',description:'Blockchain authentication for federal supply chains. DHS SVIP pathway, ITAR compliance, CBP import verification, and FDA DSCSA integration.'};
export default function GovernmentPage(){
  const stats=[{v:'$1.4B',l:'Counterfeit goods seized at US ports annually'},{v:'500+',l:'Deaths from counterfeit automotive/medical parts'},{v:'$800K',l:'DHS SVIP contract pathway submitted'},{v:'ITAR',l:'Export control compliance supported'}];
  const features=[{icon:'🛡️',t:'DHS SVIP Pathway',d:'AuthiChain submitted for DHS Silicon Valley Innovation Program. Product authentication for border security and CBP import verification. SAM.gov registration in progress.'},{icon:'🚢',t:'CBP Import Authentication',d:'AUTHI-* truemark registered at manufacture. CBP agents scan at port of entry. Counterfeit flag triggers automatic seizure protocol. Reduces $1.4B annual counterfeit import losses.'},{icon:'💊',t:'FDA DSCSA Integration',d:'FDA Drug Supply Chain Security Act serialization layer. Blockchain wrapper on GS1 barcodes. Each Rx lot: AUTHI-FDA-PHA-* + supply chain ledger. Dispensing pharmacy verify before patient.'},{icon:'⚙️',t:'ITAR Export Control',d:'ITAR-controlled equipment: AUTHI-SD-ITAR-* at manufacture. Sentinel geo-impossibility flags unauthorized re-export. Archivist: chain of custody for export license compliance.'},{icon:'🏗️',t:'MIL-SPEC Parts',d:'DoD parts authentication: AUTHI-DOD-MIL-* at approved defense manufacturer. Prevents counterfeit parts in aircraft, ships, and vehicles. Guardian confirms at maintenance depot.'},{icon:'📋',t:'SAM.gov Registered',d:'AuthiChain registered with SAM.gov. UEI pending. GSA schedule eligibility in progress. Federal procurement ready for DHS SVIP, CBP, FDA, DoD contracts.'}];
  return(<div style={{maxWidth:900,margin:'0 auto',padding:'60px 20px',background:'#0a0a0a',color:'#e5e5e5',fontFamily:'sans-serif',minHeight:'100vh'}}>
    <div style={{textAlign:'center',marginBottom:60}}>
      <p style={{color:'#C9A227',fontWeight:700,letterSpacing:'.2em',fontSize:12,marginBottom:16}}>AUTHICHAIN · GOVERNMENT</p>
      <h1 style={{fontSize:48,fontWeight:800,color:'#fff',lineHeight:1.1,marginBottom:16}}>Federal-Grade Authentication.<br/>From Port to Patient.</h1>
      <p style={{fontSize:18,color:'#aaa',maxWidth:560,margin:'0 auto 32px'}}>Blockchain supply chain authentication for DHS, CBP, FDA, and DoD. SVIP pathway. SAM.gov registered. ITAR-compliant. Protecting critical supply chains.</p>
      <div style={{display:'flex',gap:16,justifyContent:'center',flexWrap:'wrap'}}>
        <a href="mailto:authichain@gmail.com?subject=Government%20Authentication%20Inquiry" style={{padding:'14px 28px',background:'#C9A227',color:'#000',fontWeight:700,textDecoration:'none',borderRadius:8}}>Contact Government Sales →</a>
      </div>
    </div>
    <div style={{display:'grid',gridTemplateColumns:'repeat(4,1fr)',gap:16,marginBottom:60}}>{stats.map((s,i)=><div key={i} style={{background:'#111',border:'1px solid #C9A22740',borderRadius:12,padding:24,textAlign:'center'}}><div style={{fontSize:22,fontWeight:800,color:'#C9A227',marginBottom:8}}>{s.v}</div><p style={{color:'#888',fontSize:13,margin:0}}>{s.l}</p></div>)}</div>
    <div style={{display:'grid',gridTemplateColumns:'repeat(3,1fr)',gap:24}}>{features.map((f,i)=><div key={i} style={{background:'#111',border:'1px solid #ffffff10',borderRadius:12,padding:24}}><div style={{fontSize:28,marginBottom:12}}>{f.icon}</div><h3 style={{color:'#fff',marginBottom:8,fontSize:16}}>{f.t}</h3><p style={{color:'#888',fontSize:14,lineHeight:1.5}}>{f.d}</p></div>)}</div>
  </div>);
}
