export const metadata={title:'AuthiChain for Jewelry — Diamond & Gemstone Provenance Authentication',description:'Blockchain provenance for fine jewelry. Every diamond, gem, and precious metal piece gets a verifiable certificate of origin, cutting, and ownership.'};
export default function JewelryPage(){
  const stats=[{v:'$2.4B',l:'Counterfeit jewelry market annually'},{v:'1 in 4',l:'Online jewelry purchases involve misrepresentation'},{v:'$QRON',l:'Consumer rewards for authenticating purchases'},{v:'100%',l:'AuthiChain certificate accuracy'}];
  const features=[{icon:'💎',t:'Diamond Provenance',d:'Each stone: AUTHI-JWLY-DIA-* at mine or cutter. Archivist: mine of origin, cut date, carat weight, GIA report number. Blockchain-anchored. No more blood diamond risk.'},{icon:'🏅',t:'Metal Purity Verification',d:'18K, 22K, 24K gold purity claims verified via hallmarking event on-chain. Sterling silver, platinum: assay certificate anchored to AUTHI-JWLY-MTL-* truemark.'},{icon:'🔗',t:'Ownership Chain',d:'Secondary market sales: each ownership transfer creates a verified provenance event. Archivist builds complete ownership history. Estate pieces fully traceable.'},{icon:'🏪',t:'Retailer Authentication',d:'Retailer scans stone before setting. Confirms provenance chain is intact. QRON art QR embedded in packaging: consumer verify at purchase.'},{icon:'📸',t:'Insurance & Appraisal',d:'Insurance companies and appraisers access blockchain certificate directly. Theft recovery: unique AUTHI-* ID enables international identification.'},{icon:'⚡',t:'EU Critical Minerals DPP',d:'EU Critical Raw Materials Act requires mineral traceability 2026. AuthiChain DPP auto-generated for every gemstone: origin, responsible sourcing, sustainability score.'}];
  return(<div style={{maxWidth:900,margin:'0 auto',padding:'60px 20px',background:'#0a0a0a',color:'#e5e5e5',fontFamily:'sans-serif',minHeight:'100vh'}}>
    <div style={{textAlign:'center',marginBottom:60}}>
      <p style={{color:'#C9A227',fontWeight:700,letterSpacing:'.2em',fontSize:12,marginBottom:16}}>AUTHICHAIN · FINE JEWELRY</p>
      <h1 style={{fontSize:48,fontWeight:800,color:'#fff',lineHeight:1.1,marginBottom:16}}>From Mine to Ring.<br/>Every Stone Verified.</h1>
      <p style={{fontSize:18,color:'#aaa',maxWidth:560,margin:'0 auto 32px'}}>Blockchain provenance for diamonds, gemstones, and precious metals. GIA certificate anchoring, ownership chain, and responsible sourcing proof.</p>
      <a href="/pricing" style={{display:'inline-block',padding:'14px 28px',background:'#C9A227',color:'#000',fontWeight:700,textDecoration:'none',borderRadius:8}}>Start Free →</a>
    </div>
    <div style={{display:'grid',gridTemplateColumns:'repeat(4,1fr)',gap:16,marginBottom:60}}>{stats.map((s,i)=><div key={i} style={{background:'#111',border:'1px solid #C9A22740',borderRadius:12,padding:24,textAlign:'center'}}><div style={{fontSize:24,fontWeight:800,color:'#C9A227',marginBottom:8}}>{s.v}</div><p style={{color:'#888',fontSize:13,margin:0}}>{s.l}</p></div>)}</div>
    <div style={{display:'grid',gridTemplateColumns:'repeat(3,1fr)',gap:24}}>{features.map((f,i)=><div key={i} style={{background:'#111',border:'1px solid #ffffff10',borderRadius:12,padding:24}}><div style={{fontSize:28,marginBottom:12}}>{f.icon}</div><h3 style={{color:'#fff',marginBottom:8,fontSize:16}}>{f.t}</h3><p style={{color:'#888',fontSize:14,lineHeight:1.5}}>{f.d}</p></div>)}</div>
  </div>);
}
